### ISSUE TITLE
No module named clinit

### ISSUE THREAD

**Issue by curry1990** [pierrepaleo/sift_pyocl#5]
>>> import sift_pyocl
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Library/Python/2.7/lib/python/site-packages/sift_pyocl/__init__.py", line 31, in <module>
    from .plan import SiftPlan
  File "/Library/Python/2.7/lib/python/site-packages/sift_pyocl/plan.py", line 63, in <module>
    from .clinit import ocl, pyopencl, kernel_workgroup_size
ImportError: No module named clinit

I can't find package named .clinit. Anybody help? 

Thanks!

**Comment by FrancoisDuBois92** [comment]
I too find the same error.  Any solution found yet?

**Comment by pierrepaleo** [comment]
Hi,

As mentioned in a [previous issue](https://github.com/pierrepaleo/sift_pyocl/issues/2#issuecomment-267140130), this repository is no longer maintained. SIFT-Opencl is now part of a larger project, where maintenance/improvement efforts are dedicated.

I understand that installing a whole larger project is not convenient when we are only looking for SIFT+OpenCL. There are plans to isolate the new version of SIFT/OpenCL in a dedicated repository in the future.

Best regards,

Pierre

**Comment by FrancoisDuBois92** [comment]
So will I be able to use the SIFT-OpenCL module that is in the silx project?

**Comment by pierrepaleo** [comment]
Yes, it should work. As far as I know it is currently being used through silx.

**Comment by burcuamirgan** [comment]
Hello
I have 2 large satellite images. And I split this images. My aim is to match together .  But I get a "MEM_OBJECT_ALLOCATION_FAILURE" error. 
 I cannot delete the gpu memory used after processing each part in the loop.
Is there a way to reset GPU memory?
